# Generated by Django 5.2.7 on 2025-10-31 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Embrion', '0003_alter_embrion_calidad_alter_embrion_estado'),
        ('Tratamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_positivo', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('embriones', models.ManyToManyField(related_name='transferencias', to='Embrion.embrion')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='Tratamiento.tratamiento')),
            ],
            options={
                'db_table': 'transferencia',
                'ordering': ['-created_at'],
            },
        ),
    ]
