# Generated by Django 5.2.7 on 2025-11-13 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Embrion', '0003_alter_embrion_calidad_alter_embrion_estado'),
        ('Transferencia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='quirofano',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='realizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TransferenciaEmbrion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('quirofano', models.CharField(blank=True, max_length=120, null=True)),
                ('test_positivo', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('embrion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_item', to='Embrion.embrion')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencia_items_realizados', to=settings.AUTH_USER_MODEL)),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_embrios', to='Transferencia.transferencia')),
            ],
            options={
                'db_table': 'transferencia_embrion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='embriones',
        ),
        migrations.AddField(
            model_name='transferencia',
            name='embriones',
            field=models.ManyToManyField(blank=True, related_name='transferencias', through='Transferencia.TransferenciaEmbrion', to='Embrion.embrion'),
        ),
    ]
