# Generated by Django 5.2.7 on 2025-10-20 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PrimerConsulta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estudio', models.CharField(choices=[('ginecologico', 'Ginecológico'), ('hormonal', 'Hormonal'), ('semen', 'Semen'), ('prequirurgico', 'Prequirúrgico')], max_length=50)),
                ('pdf_url', models.URLField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('primera_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='PrimerConsulta.primeraconsulta')),
            ],
        ),
    ]
