# Generated by Django 5.2.7 on 2025-10-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='user_gender',
            field=models.CharField(default='Femenino', max_length=50),
        ),
    ]
