# Generated by Django 5.2.7 on 2025-10-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
