# Generated by Django 5.2.7 on 2025-10-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0002_medico_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='id',
        ),
        migrations.AlterField(
            model_name='medico',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='medico',
            table='medico',
        ),
    ]
