# Generated by Django 5.2.7 on 2025-10-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0003_remove_medico_id_alter_medico_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
