# Generated by Django X.Y on 2025-10-14
from django.db import migrations, models

class Migration(migrations.Migration):

	initial = True

	dependencies = [
		('Ovocito', '0001_initial'),
	]

	operations = [
		migrations.CreateModel(
			name='Embrion',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('identificador', models.CharField(max_length=50, unique=True)),
				('fecha_fertilizacion', models.DateField()),
				('tecnica', models.CharField(max_length=100)),
				('tecnico_laboratorio', models.CharField(max_length=100)),
				('calidad', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
				('estado', models.CharField(max_length=20, choices=[('transferido', 'Transferido'), ('no_transferido', 'No transferido')])),
				('fecha_alta', models.DateField()),
				('fecha_baja', models.DateField(null=True, blank=True)),
				('fecha_modificacion', models.DateTimeField(auto_now=True)),
				('info_semen', models.TextField()),
				('ovocito', models.ForeignKey(on_delete=models.CASCADE, related_name='embriones', to='Ovocito.Ovocito')),
			],
		),
	]
