# Generated by Django 5.2.7 on 2025-10-20 14:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ovocito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embrion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Identificador único del embrión (EMB...)', max_length=50, unique=True)),
                ('fecha_fertilizacion', models.DateField(help_text='Fecha de fertilización')),
                ('tecnica', models.CharField(help_text='Técnica utilizada', max_length=100)),
                ('tecnico_laboratorio', models.CharField(help_text='Técnico de laboratorio responsable', max_length=100)),
                ('calidad', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Calidad del embrión (1-5)')),
                ('estado', models.CharField(choices=[('transferido', 'Transferido'), ('no_transferido', 'No transferido')], help_text='Estado del embrión', max_length=20)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now, help_text='Fecha de alta')),
                ('fecha_baja', models.DateField(blank=True, help_text='Fecha de baja', null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación')),
                ('info_semen', models.TextField(help_text='Información del semen')),
                ('ovocito', models.ForeignKey(help_text='Ovocito relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='embriones', to='Ovocito.ovocito')),
            ],
        ),
    ]
