# Generated by Django 5.2.7 on 2025-10-17 16:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Embrion', '0001_initial'),
        ('Ovocito', '0002_ovocito_puncion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embrion',
            name='calidad',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Calidad del embrión (1-5)'),
        ),
        migrations.AlterField(
            model_name='embrion',
            name='estado',
            field=models.CharField(choices=[('transferido', 'Transferido'), ('no_transferido', 'No transferido')], help_text='Estado del embrión', max_length=20),
        ),
        migrations.AlterField(
            model_name='embrion',
            name='fecha_alta',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='embrion',
            name='fecha_baja',
            field=models.DateField(blank=True, help_text='Fecha de baja', null=True),
        ),
        migrations.AlterField(
            model_name='embrion',
            name='fecha_fertilizacion',
            field=models.DateField(help_text='Fecha de fertilización'),
        ),
        migrations.AlterField(
            model_name='embrion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de última modificación'),
        ),
        migrations.AlterField(
            model_name='embrion',
            name='identificador',
            field=models.CharField(help_text='Identificador único del embrión (EMB...)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='embrion',
            name='info_semen',
            field=models.TextField(help_text='Información del semen'),
        ),
        migrations.AlterField(
            model_name='embrion',
            name='ovocito',
            field=models.ForeignKey(help_text='Ovocito relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='embriones', to='Ovocito.ovocito'),
        ),
        migrations.AlterField(
            model_name='embrion',
            name='tecnica',
            field=models.CharField(help_text='Técnica utilizada', max_length=100),
        ),
        migrations.AlterField(
            model_name='embrion',
            name='tecnico_laboratorio',
            field=models.CharField(help_text='Técnico de laboratorio responsable', max_length=100),
        ),
    ]
