# Generated by Django 5.2.7 on 2025-10-20 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Embrion', '0001_initial'),
        ('Fertilizacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embrion',
            name='fecha_alta',
        ),
        migrations.RemoveField(
            model_name='embrion',
            name='fecha_fertilizacion',
        ),
        migrations.RemoveField(
            model_name='embrion',
            name='info_semen',
        ),
        migrations.RemoveField(
            model_name='embrion',
            name='ovocito',
        ),
        migrations.RemoveField(
            model_name='embrion',
            name='tecnica',
        ),
        migrations.RemoveField(
            model_name='embrion',
            name='tecnico_laboratorio',
        ),
        migrations.AddField(
            model_name='embrion',
            name='causa_descarte',
            field=models.TextField(blank=True, help_text='Causa de descarte del embrión', null=True),
        ),
        migrations.AddField(
            model_name='embrion',
            name='fertilizacion',
            field=models.OneToOneField(help_text='Fertilización de la cual proviene este embrión', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embrion', to='Fertilizacion.fertilizacion'),
        ),
        migrations.AddField(
            model_name='embrion',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones adicionales sobre el embrión', null=True),
        ),
        migrations.AddField(
            model_name='embrion',
            name='pgt',
            field=models.CharField(blank=True, choices=[('exitoso', 'Exitoso'), ('no exitoso', 'No Exitoso')], default='no realizado', help_text='Resultado del PGT', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='embrion',
            name='estado',
            field=models.CharField(choices=[('transferido', 'Transferido'), ('criopreservado', 'Criopreservado'), ('descartado', 'Descartado'), ('fresco', 'Fresco')], help_text='Estado del embrión', max_length=20),
        ),
        migrations.AlterField(
            model_name='embrion',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, help_text='Fecha de baja del embrión', null=True),
        ),
    ]
