# Generated by Django 5.2.7 on 2025-10-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Embrion', '0002_remove_embrion_fecha_alta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embrion',
            name='calidad',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Calidad del embrión (1-5)', null=True),
        ),
        migrations.AlterField(
            model_name='embrion',
            name='estado',
            field=models.CharField(choices=[('transferido', 'Transferido'), ('no transferido', 'No Transferido'), ('criopreservado', 'Criopreservado'), ('descartado', 'Descartado'), ('fresco', 'Fresco')], help_text='Estado del embrión', max_length=20),
        ),
    ]
