# Generated by Django 5.2.7 on 2025-11-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Embrion', '0003_alter_embrion_calidad_alter_embrion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embrion',
            name='estado',
            field=models.CharField(default='Fresco', help_text='Estado del embrión', max_length=20),
        ),
    ]
