# Generated by Django 5.2.7 on 2025-12-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Embrion', '0004_alter_embrion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embrion',
            name='pgt',
            field=models.CharField(blank=True, choices=[('exitoso', 'Exitoso'), ('no_exitoso', 'No Exitoso')], default='no realizado', help_text='Resultado del PGT', max_length=20, null=True),
        ),
    ]
