# Generated by Django 5.2.7 on 2025-10-17 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ovocito', '0002_ovocito_puncion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizacion',
            fields=[
                ('id_fertilizacion', models.AutoField(primary_key=True, serialize=False)),
                ('semen_info', models.CharField(blank=True, help_text='Identificador o notas del semen utilizado', max_length=150, null=True)),
                ('semen_id', models.IntegerField(blank=True, help_text='ID del semen si existe una entidad externa', null=True)),
                ('fecha_fertilizacion', models.DateField()),
                ('tecnica_icsi', models.BooleanField(default=False, help_text='True si la técnica fue ICSI')),
                ('tecnica_fiv', models.BooleanField(default=False, help_text='True si la técnica fue FIV')),
                ('resultado', models.CharField(choices=[('exitosa', 'Exitosa'), ('no_exitosa', 'No exitosa')], default='no_exitosa', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ovocito', models.ForeignKey(help_text='Ovocito sobre el que se realizó la fertilización', on_delete=django.db.models.deletion.CASCADE, related_name='fertilizaciones', to='Ovocito.ovocito')),
                ('tecnico', models.ForeignKey(blank=True, help_text='Usuario (técnico) que registró la fertilización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fertilizaciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fertilización',
                'verbose_name_plural': 'Fertilizaciones',
                'ordering': ['-fecha_fertilizacion', '-created_at'],
            },
        ),
    ]
