# Generated by Django 5.2.7 on 2025-10-20 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ovocito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizacion',
            fields=[
                ('id_fertilizacion', models.AutoField(primary_key=True, serialize=False)),
                ('semen_info', models.CharField(blank=True, help_text='Identificador o notas del semen utilizado', max_length=150, null=True)),
                ('semen_id', models.IntegerField(blank=True, help_text='ID del semen si existe una entidad externa', null=True)),
                ('fecha_fertilizacion', models.DateField()),
                ('tecnico_laboratorio', models.CharField(blank=True, help_text='Nombre del técnico que registró la fertilización', max_length=100, null=True)),
                ('tecnica_icsi', models.BooleanField(default=False, help_text='True si la técnica fue ICSI')),
                ('tecnica_fiv', models.BooleanField(default=False, help_text='True si la técnica fue FIV')),
                ('resultado', models.CharField(choices=[('exitosa', 'Exitosa'), ('no_exitosa', 'No exitosa')], default='no_exitosa', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ovocito', models.ForeignKey(help_text='Ovocito sobre el que se realizó la fertilización', on_delete=django.db.models.deletion.CASCADE, related_name='fertilizaciones', to='Ovocito.ovocito')),
            ],
            options={
                'db_table': 'fertilizacion',
                'ordering': ['-fecha_fertilizacion', '-created_at'],
            },
        ),
    ]
