# Generated by Django 5.2.7 on 2025-10-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fertilizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fertilizacion',
            options={'ordering': ['-fecha_fertilizacion', '-created_at']},
        ),
        migrations.AlterModelTable(
            name='fertilizacion',
            table='fertilizacion',
        ),
    ]
