# Generated by Django 5.2.7 on 2025-11-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fertilizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizacion',
            name='banco_semen_id',
            field=models.IntegerField(blank=True, help_text='ID del semen del banco cuando se requiere por coincidencia fenotípica', null=True),
        ),
        migrations.AddField(
            model_name='fertilizacion',
            name='razon_banco_semen',
            field=models.CharField(choices=[('semen_no_ok', 'Semen de pareja masculina no apto'), ('pareja_femenina', 'Pareja femenina - requiere banco'), ('sin_pareja', 'Sin pareja - requiere banco'), ('no_aplica', 'No requiere banco de semen')], default='no_aplica', help_text='Razón por la cual se usa banco de semen', max_length=20),
        ),
    ]
