# Generated by Django 5.2.7 on 2025-12-04 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fertilizacion', '0002_fertilizacion_banco_semen_id_and_more'),
        ('Ovocito', '0004_ovocito_usado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizacion',
            name='ovocito_donado_id',
            field=models.IntegerField(blank=True, help_text='ID del ovocito donado del banco externo (Supabase)', null=True),
        ),
        migrations.AddField(
            model_name='fertilizacion',
            name='ovocito_donado_info',
            field=models.CharField(blank=True, help_text='Identificador del ovocito donado (ej: OVO-DON-12345678)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizacion',
            name='ovocito',
            field=models.ForeignKey(blank=True, help_text='Ovocito sobre el que se realizó la fertilización (NULL si es donado)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fertilizaciones', to='Ovocito.ovocito'),
        ),
    ]
