# Generated by Django 5.2.7 on 2025-10-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fertilizacion', '0002_alter_fertilizacion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizacion',
            name='tecnico',
        ),
        migrations.AddField(
            model_name='fertilizacion',
            name='tecnico_laboratorio',
            field=models.CharField(blank=True, help_text='Nombre del técnico que registró la fertilización', max_length=100, null=True),
        ),
    ]
