# Generated by Django 5.2.7 on 2025-12-13 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fertilizacion', '0003_fertilizacion_ovocito_donado_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizacion',
            name='paciente',
            field=models.ForeignKey(blank=True, help_text='Paciente al que pertenece esta fertilización (redundante con Ovocito.paciente, ayuda a consultas rápidas)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fertilizaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
