# Generated by Django 5.2.7 on 2025-11-07 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ovocito', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialOvocito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(help_text='Estado registrado para el ovocito', max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('ovocito', models.ForeignKey(help_text='Ovocito al que pertenece este registro de historial', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='Ovocito.ovocito')),
                ('paciente', models.ForeignKey(help_text='Paciente propietario del ovocito', on_delete=django.db.models.deletion.CASCADE, related_name='historial_ovocitos', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que registró el evento (medico/técnico)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_registrado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial Ovocito',
                'verbose_name_plural': 'Historial Ovocitos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['ovocito', 'paciente'], name='Historial_o_ovocito_821efa_idx'), models.Index(fields=['fecha'], name='Historial_o_fecha_690fcd_idx')],
            },
        ),
    ]
