# Generated by Django 5.2.7 on 2025-10-18 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PrimerConsulta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentesGinecologicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menarca', models.PositiveSmallIntegerField(blank=True, help_text='Edad en años de la primera menstruación (menarca).', null=True)),
                ('ciclo_menstrual', models.PositiveSmallIntegerField(blank=True, help_text='Duración típica del ciclo menstrual en días (por ejemplo: 28).', null=True)),
                ('regularidad', models.CharField(blank=True, choices=[('regular', 'Regular'), ('irregular', 'Irregular')], help_text='Indica si los ciclos son regulares o irregulares.', max_length=20, null=True)),
                ('duracion_menstrual_dias', models.PositiveSmallIntegerField(blank=True, help_text='Duración típica del sangrado menstrual en días.', null=True)),
                ('caracteristicas_sangrado', models.CharField(blank=True, choices=[('leve', 'Leve'), ('moderado', 'Moderado'), ('abundante', 'Abundante'), ('intermitente', 'Intermitente')], help_text='Características típicas del sangrado menstrual.', max_length=20, null=True)),
                ('g', models.PositiveIntegerField(blank=True, help_text='Número total de embarazos (G).', null=True)),
                ('p', models.PositiveIntegerField(blank=True, help_text='Número de partos a término (P).', null=True)),
                ('ab', models.PositiveIntegerField(blank=True, help_text='Número de abortos (AB).', null=True)),
                ('st', models.PositiveIntegerField(blank=True, help_text='Número de embarazos ectópicos (ST).', null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_ginecologicos', to='PrimerConsulta.primeraconsulta')),
            ],
        ),
    ]
