# Generated by Django 5.2.7 on 2025-11-22 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tratamiento', '0007_tratamiento_motivo_finalizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_beta', models.BooleanField(default=False, help_text='Resultado de la prueba Beta HCG (True=Positiva, False=Negativa).', null=True)),
                ('hay_saco_gestacional', models.BooleanField(default=False, help_text='Confirmación de saco gestacional mediante ecografía.')),
                ('embarazo_clinico', models.BooleanField(default=False, help_text='Confirmación de latido cardíaco fetal (define embarazo clínico).')),
                ('nacido_vivo', models.BooleanField(default=False, help_text='Resultado final: indica si el bebé nació vivo.')),
                ('fecha_seguimiento', models.DateField(auto_now_add=True)),
                ('tratamiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento_beta', to='Tratamiento.tratamiento')),
            ],
            options={
                'verbose_name': 'Seguimiento de Resultado',
                'verbose_name_plural': 'Seguimiento de Resultados',
            },
        ),
    ]
