# Generated by Django 5.2.7 on 2025-12-10 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seguimiento', '0001_initial'),
        ('Transferencia', '0002_transferencia_fecha_transferencia_quirofano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientotratamiento',
            name='cantidad_nacimientos',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Número de bebés nacidos vivos en este evento.', null=True),
        ),
        migrations.AddField(
            model_name='seguimientotratamiento',
            name='causa',
            field=models.TextField(blank=True, help_text='Causa o explicación del resultado, especialmente si es negativo o hay complicaciones.', null=True),
        ),
        migrations.AddField(
            model_name='seguimientotratamiento',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del bebé/s.', null=True),
        ),
        migrations.AddField(
            model_name='seguimientotratamiento',
            name='id_transferencia',
            field=models.ForeignKey(blank=True, help_text='Identificador de la transferencia de embriones a la que corresponde este seguimiento.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Transferencia.transferencia'),
        ),
        migrations.AlterField(
            model_name='seguimientotratamiento',
            name='nacido_vivo',
            field=models.BooleanField(blank=True, default=None, help_text='Resultado final: True si el bebé nació vivo, False si no, NULL si está pendiente.', null=True),
        ),
    ]
