# Generated by Django 5.2.7 on 2025-10-31 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del tratamiento', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del tratamiento')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del tratamiento')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el tratamiento está activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('medico', models.ForeignKey(help_text='Médico responsable del tratamiento', limit_choices_to={'rol': 'medico'}, on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos_asignados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(help_text='Paciente al que se le asigna este tratamiento', limit_choices_to={'rol': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
