# Generated by Django 5.2.7 on 2025-11-01 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0002_alter_monitoreo_options_and_more'),
        ('PrimerConsulta', '0002_primeraconsulta_antecedentes_clinicos_1_and_more'),
        ('Puncion', '0001_initial'),
        ('Transferencia', '0001_initial'),
        ('Tratamiento', '0001_initial'),
        ('Turnos', '0004_alter_turno_id_externo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamiento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tratamiento',
            name='nombre',
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='monitoreos',
            field=models.ManyToManyField(help_text='Monitoreos asociados a este tratamiento', related_name='tratamientos', to='Monitoreo.monitoreo'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='objetivo',
            field=models.TextField(blank=True, help_text='Descripción detallada del tratamiento'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='primera_consulta',
            field=models.ForeignKey(blank=True, help_text='Primera consulta asociada al tratamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamientos', to='PrimerConsulta.primeraconsulta'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='puncion',
            field=models.ForeignKey(blank=True, help_text='Punción asociada al tratamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punciones', to='Puncion.puncion'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='transferencia',
            field=models.ForeignKey(blank=True, help_text='Transferencia asociada al tratamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias', to='Transferencia.transferencia'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='turnos',
            field=models.ManyToManyField(help_text='Turnos asociados a este tratamiento', related_name='tratamientos', to='Turnos.turno'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='medico',
            field=models.ForeignKey(help_text='Médico responsable del tratamiento', limit_choices_to={'rol': 'MEDICO'}, on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
