# Generated by Django 5.2.7 on 2025-11-01 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SegundaConsulta', '0001_initial'),
        ('Tratamiento', '0002_remove_tratamiento_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='segunda_consulta',
            field=models.ForeignKey(blank=True, help_text='Segunda consulta asociada al tratamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamientos', to='SegundaConsulta.segundaconsulta'),
        ),
    ]
