# Generated by Django 5.2.7 on 2025-11-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tratamiento', '0002_remove_tratamiento_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamiento',
            name='monitoreos',
        ),
    ]
