# Generated by Django 5.2.7 on 2025-11-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tratamiento', '0003_tratamiento_segunda_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True, help_text='Fecha de inicio del tratamiento'),
        ),
    ]
