# Generated by Django 5.2.7 on 2025-11-01 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimerConsulta', '0003_remove_primeraconsulta_medico_and_more'),
        ('Puncion', '0001_initial'),
        ('SegundaConsulta', '0002_remove_segundaconsulta_primera_consulta'),
        ('Transferencia', '0001_initial'),
        ('Tratamiento', '0004_alter_tratamiento_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='primera_consulta',
            field=models.OneToOneField(blank=True, help_text='Primera consulta asociada al tratamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamiento', to='PrimerConsulta.primeraconsulta'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='puncion',
            field=models.OneToOneField(blank=True, help_text='Punción asociada al tratamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puncion', to='Puncion.puncion'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='segunda_consulta',
            field=models.OneToOneField(blank=True, help_text='Segunda consulta asociada al tratamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamiento', to='SegundaConsulta.segundaconsulta'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='transferencia',
            field=models.OneToOneField(blank=True, help_text='Transferencia asociada al tratamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencia', to='Transferencia.transferencia'),
        ),
    ]
