# Generated by Django 5.2.7 on 2025-11-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tratamiento', '0003_remove_tratamiento_monitoreos'),
        ('Tratamiento', '0005_alter_tratamiento_primera_consulta_and_more'),
    ]

    operations = [
    ]
