# Generated by Django 5.2.7 on 2025-11-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tratamiento', '0006_merge_20251102_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='motivo_finalizacion',
            field=models.TextField(blank=True, help_text='Motivo por el cual se finalizó el tratamiento'),
        ),
    ]
