# Generated by Django 5.2.7 on 2025-11-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tratamiento', '0007_tratamiento_motivo_finalizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='id_pago',
            field=models.IntegerField(blank=True, help_text='ID del pago asociado al tratamiento', null=True),
        ),
    ]
