# Generated by Django 5.2.7 on 2025-11-13 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Embrion', '0003_alter_embrion_calidad_alter_embrion_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEmbrion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(help_text='Estado registrado para el embrion', max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('embrion', models.ForeignKey(help_text='Embrion al que pertenece este registro de historial', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='Embrion.embrion')),
                ('paciente', models.ForeignKey(help_text='Paciente propietario del embrion', on_delete=django.db.models.deletion.CASCADE, related_name='historial_embriones', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que registró el evento (medico/técnico)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_embrion_registrado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial Embrion',
                'verbose_name_plural': 'Historial Embriones',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['embrion', 'paciente'], name='Historial_e_embrion_adde95_idx'), models.Index(fields=['fecha'], name='Historial_e_fecha_8b4d2c_idx')],
            },
        ),
    ]
