# Generated by Django 5.2.7 on 2025-11-14 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Embrion', '0003_alter_embrion_calidad_alter_embrion_estado'),
        ('Historial_embrion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialembrion',
            options={'ordering': ['-fecha_modificacion'], 'verbose_name': 'Historial de Embrión', 'verbose_name_plural': 'Historiales de Embriones'},
        ),
        migrations.RemoveIndex(
            model_name='historialembrion',
            name='Historial_e_embrion_adde95_idx',
        ),
        migrations.RemoveIndex(
            model_name='historialembrion',
            name='Historial_e_fecha_8b4d2c_idx',
        ),
        migrations.RenameField(
            model_name='historialembrion',
            old_name='fecha',
            new_name='fecha_modificacion',
        ),
        migrations.RenameField(
            model_name='historialembrion',
            old_name='nota',
            new_name='observaciones',
        ),
        migrations.RemoveField(
            model_name='historialembrion',
            name='paciente',
        ),
        migrations.AddField(
            model_name='historialembrion',
            name='calidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historialembrion',
            name='tipo_modificacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historialembrion',
            name='embrion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='Embrion.embrion'),
        ),
        migrations.AlterField(
            model_name='historialembrion',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historialembrion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historialembrion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_embrion_registrado', to=settings.AUTH_USER_MODEL),
        ),
    ]
