# Generated by Django 5.2.7 on 2025-11-14 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historial_embrion', '0002_alter_historialembrion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialembrion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Historial Embrion', 'verbose_name_plural': 'Historial Embriones'},
        ),
        migrations.AddField(
            model_name='historialembrion',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historialembrion',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialembrion',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_embriones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialembrion',
            name='estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historialembrion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
