# Generated by Django 5.2.7 on 2025-10-09 04:05

import Paciente.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚ\\s]+$', 'Solo se permiten letras.')])),
                ('apellido', models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚ\\s]+$', 'Solo se permiten letras.')])),
                ('fecha_nacimiento', models.DateField(validators=[Paciente.models.validar_fecha_nacimiento])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Debe ingresar un correo válido.')])),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.'), django.core.validators.MinLengthValidator(8, 'El teléfono debe tener al menos 8 dígitos.')])),
                ('obra_social', models.CharField(default='', max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10)),
                ('contraseña', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(6, 'La contraseña debe tener al menos 6 caracteres.')])),
                ('numero_afiliado', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.')])),
                ('dni', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.'), django.core.validators.MinLengthValidator(7, 'El DNI debe tener al menos 7 dígitos.')])),
            ],
            options={
                'db_table': 'Paciente',
            },
        ),
    ]
