# Generated by Django 5.2.7 on 2025-10-20 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PrimerConsulta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudio', models.CharField(max_length=100)),
                ('tipo_estudio', models.CharField(blank=True, max_length=50, null=True)),
                ('valor', models.CharField(blank=True, max_length=255, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_estudios', to='PrimerConsulta.primeraconsulta')),
            ],
        ),
    ]
