# Generated by Django 5.2.7 on 2025-11-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultadoEstudio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoestudio',
            name='persona',
            field=models.CharField(choices=[('PACIENTE', 'Paciente principal'), ('ACOMPAÑANTE', 'Pareja / acompañante')], default='PACIENTE', max_length=20),
        ),
    ]
