# Generated by Django 5.2.7 on 2025-10-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='obra_social',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
