# Generated by Django 5.2.7 on 2025-10-20 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dni',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.'), django.core.validators.MinLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='firma_medico',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_medicos/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('MEDICO', 'Médico'), ('ADMIN', 'Administrativo'), ('LAB_OPERATOR', 'Operador de laboratorio'), ('DIRECTOR_MEDICO', 'Director Médico')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.')]),
        ),
    ]
