# Generated by Django 5.2.7 on 2025-11-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0002_alter_customuser_obra_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('PACIENTE', 'Paciente'), ('MEDICO', 'Médico'), ('ADMIN', 'Administrativo'), ('OPERADOR_LABORATORIO', 'Operador de laboratorio'), ('DIRECTOR_MEDICO', 'Director Médico')], help_text='Tipo de usuario dentro del sistema', max_length=20),
        ),
    ]
