# Generated by Django 5.2.7 on 2025-11-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0003_alter_customuser_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='director_medico',
            field=models.BooleanField(default=False),
        ),
    ]
