# Generated by Django 5.2.7 on 2025-11-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0004_customuser_director_medico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='director_medico',
            new_name='is_director',
        ),
    ]
