# Generated by Django 5.2.7 on 2025-10-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentesPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuma_pack_dias', models.CharField(blank=True, help_text='Ej: 10 cigarrillos/día * 5 años / 20 = 2.5', max_length=6, null=True, verbose_name='fuma (pack-días)')),
                ('consume_alcohol', models.CharField(blank=True, help_text='Ej: 2 veces por semana, cerveza', max_length=255, verbose_name='consume alcohol (frecuencia y tipo)')),
                ('drogas_recreativas', models.CharField(blank=True, help_text='Ej: marihuana ocasional', max_length=255, verbose_name='drogas recreativas')),
                ('observaciones_habitos', models.TextField(blank=True, help_text='Observaciones libres sobre hábitos', verbose_name='observaciones sobre hábitos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Antecedente personal',
                'verbose_name_plural': 'Antecedentes personales',
            },
        ),
    ]
