# Generated by Django 5.2.7 on 2025-10-20 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AntecedentesPersonales', '0001_initial'),
        ('PrimerConsulta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentespersonales',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_personales', to='PrimerConsulta.primeraconsulta'),
        ),
    ]
