# Generated by Django 5.2.7 on 2025-10-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AntecedentesPersonales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentespersonales',
            name='fuma_pack_dias',
            field=models.CharField(blank=True, help_text='Ej: 10 cigarrillos/día * 5 años / 20 = 2.5', max_length=6, null=True, verbose_name='fuma (pack-días)'),
        ),
    ]
