# Generated by Django 5.2.7 on 2025-10-20 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimeraConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo_consulta', models.TextField(blank=True, null=True)),
                ('antecedentes_familiares_1', models.TextField(blank=True, null=True)),
                ('antecedentes_familiares_2', models.TextField(blank=True, null=True)),
                ('antecedentes_genitales', models.TextField(blank=True, null=True)),
                ('antecedentes_quirurgicos_1', models.TextField(blank=True, null=True)),
                ('antecedentes_quirurgicos_2', models.TextField(blank=True, null=True)),
                ('examen_fisico_1', models.TextField(blank=True, null=True)),
                ('examen_fisico_2', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primeras_consultas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primeras_consultas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
