# Generated by Django 5.2.7 on 2025-10-18 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medicos', '0004_medico_eliminado'),
        ('Paciente', '0002_remove_paciente_apellido_remove_paciente_contraseña_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimeraConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo_consulta', models.TextField()),
                ('antecedentes_familiares_1', models.TextField()),
                ('antecedentes_familiares_2', models.TextField(blank=True, null=True)),
                ('antecedentes_genitales', models.TextField(blank=True, null=True)),
                ('antecedentes_quirurgicos_1', models.TextField(blank=True, null=True)),
                ('antecedentes_quirurgicos_2', models.TextField(blank=True, null=True)),
                ('examen_fisico_1', models.TextField(blank=True, null=True)),
                ('examen_fisico_2', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primeras_consultas_realizadas', to='Medicos.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primeras_consultas', to='Paciente.paciente')),
            ],
        ),
    ]
