# Generated by Django 5.2.7 on 2025-10-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimerConsulta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='primeraconsulta',
            name='antecedentes_clinicos_1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='primeraconsulta',
            name='antecedentes_clinicos_2',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
