# Generated by Django 5.2.7 on 2025-10-18 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0002_remove_paciente_apellido_remove_paciente_contraseña_and_more'),
        ('PrimerConsulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primeraconsulta',
            name='antecedentes_familiares_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='primeraconsulta',
            name='objetivo_consulta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='primeraconsulta',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primeras_consultas', to='Paciente.paciente'),
        ),
    ]
