# Generated by Django 5.2.7 on 2025-11-01 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrimerConsulta', '0002_primeraconsulta_antecedentes_clinicos_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primeraconsulta',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='primeraconsulta',
            name='paciente',
        ),
    ]
