# Generated by Django 5.2.7 on 2025-10-28 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción del monitoreo', max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del monitoreo')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación del monitoreo')),
                ('numero_monitoreos', models.IntegerField(help_text='Número de monitoreos realizados')),
                ('medico', models.ForeignKey(help_text='Médico responsable del monitoreo', limit_choices_to={'rol': 'MEDICO'}, on_delete=django.db.models.deletion.CASCADE, related_name='monitoreos_como_medico', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(help_text='Paciente al que pertenece el monitoreo', limit_choices_to={'rol': 'PACIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='monitoreos_como_paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
