# Generated by Django 5.2.7 on 2025-11-01 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0001_initial'),
        ('Tratamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoreo',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Monitoreo', 'verbose_name_plural': 'Monitoreos'},
        ),
        migrations.RemoveField(
            model_name='monitoreo',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='monitoreo',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='monitoreo',
            name='numero_monitoreos',
        ),
        migrations.RemoveField(
            model_name='monitoreo',
            name='paciente',
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='atendido',
            field=models.BooleanField(default=False, help_text='Indica si el monitoreo ya fue atendido'),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='fecha_atencion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora del turno en que se atenderá este monitoreo', null=True),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='tratamiento',
            field=models.ForeignKey(blank=True, help_text='Tratamiento al que pertenece este monitoreo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lista_monitoreos', to='Tratamiento.tratamiento'),
        ),
    ]
