# Generated by Django 5.2.7 on 2025-11-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0002_alter_monitoreo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoreo',
            name='fecha_realizado',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se atendió realmente el monitoreo', null=True),
        ),
    ]
