# Generated by Django 5.2.7 on 2025-11-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0003_monitoreo_fecha_realizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoreo',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Descripción del monitoreo', max_length=500),
        ),
    ]
