# Generated by Django 5.2.7 on 2025-10-18 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PrimerConsulta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fenotipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_ojos', models.CharField(blank=True, help_text='Ej: marrón, verde, azul', max_length=64, verbose_name='color de ojos')),
                ('color_pelo', models.CharField(blank=True, help_text='Ej: rubio, castaño, negro', max_length=64, verbose_name='color de pelo')),
                ('tipo_pelo', models.CharField(blank=True, help_text='Ej: lacio, ondulado, rizado', max_length=64, verbose_name='tipo de pelo')),
                ('altura_cm', models.PositiveSmallIntegerField(blank=True, help_text='Ej: 165', null=True, verbose_name='altura (cm)')),
                ('complexion_corporal', models.CharField(blank=True, choices=[('delgada', 'Delgada'), ('normal', 'Normal'), ('robusta', 'Robusta'), ('otra', 'Otra')], default='normal', max_length=16, verbose_name='complexión corporal')),
                ('rasgos_etnicos', models.TextField(blank=True, help_text='Ej: europeo, latino, afrodescendiente, etc.', verbose_name='rasgos étnicos generales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fenotipos', to='PrimerConsulta.primeraconsulta')),
            ],
            options={
                'verbose_name': 'Fenotipo',
                'verbose_name_plural': 'Fenotipos',
            },
        ),
    ]
