# Generated by Django 5.2.7 on 2025-11-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fenotipo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenotipo',
            name='persona',
            field=models.CharField(choices=[('PACIENTE', 'Paciente'), ('ACOMPAÑANTE', 'Acompañante')], default='PACIENTE', max_length=16, verbose_name='persona'),
        ),
    ]
