# Generated by Django 5.2.7 on 2025-11-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fenotipo', '0002_fenotipo_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fenotipo',
            name='complexion_corporal',
            field=models.CharField(blank=True, choices=[('delgada', 'Delgada'), ('media', 'Normal'), ('robusta', 'Robusta'), ('otra', 'Otra')], default='normal', max_length=16, verbose_name='complexión corporal'),
        ),
    ]
