# Generated by Django 5.2.7 on 2025-11-01 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PrimerConsulta', '0002_primeraconsulta_antecedentes_clinicos_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegundaConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ovocito_viable', models.BooleanField(default=False)),
                ('semen_viable', models.BooleanField(default=False)),
                ('consentimiento_informado', models.BinaryField(blank=True, null=True)),
                ('tipo_medicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('dosis_medicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('duracion_medicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('primera_consulta', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segunda_consulta', to='PrimerConsulta.primeraconsulta')),
            ],
        ),
    ]
