# Generated by Django 5.2.7 on 2025-11-01 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SegundaConsulta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segundaconsulta',
            name='primera_consulta',
        ),
    ]
