# Generated by Django 5.2.7 on 2025-11-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SegundaConsulta', '0002_remove_segundaconsulta_primera_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='segundaconsulta',
            name='droga',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
