# Generated by Django 5.2.7 on 2025-11-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SegundaConsulta', '0003_segundaconsulta_droga'),
    ]

    operations = [
        migrations.AddField(
            model_name='segundaconsulta',
            name='orden_droga_pdf',
            field=models.FileField(blank=True, help_text='Archivo PDF de la orden médica generada automáticamente', null=True, upload_to='ordenes_droga/'),
        ),
        migrations.AlterField(
            model_name='segundaconsulta',
            name='consentimiento_informado',
            field=models.FileField(blank=True, help_text='Archivo PDF del consentimiento informado', null=True, upload_to='consentimientos/'),
        ),
    ]
