# Generated by Django 5.2.7 on 2025-10-17 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medicos', '0003_remove_medico_id_alter_medico_dni_and_more'),
        ('Paciente', '0002_remove_paciente_apellido_remove_paciente_contraseña_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('idMedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='Medicos.medico')),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='Paciente.paciente')),
            ],
            options={
                'db_table': 'turno',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
