# Generated by Django 5.2.7 on 2025-10-25 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Medico', models.ForeignKey(limit_choices_to={'rol': 'MEDICO'}, on_delete=django.db.models.deletion.CASCADE, related_name='turnos_medico', to=settings.AUTH_USER_MODEL)),
                ('Paciente', models.ForeignKey(limit_choices_to={'rol': 'PACIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='turnos_paciente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'turno',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
