# Generated by Django 5.2.7 on 2025-10-17 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='idMedico',
            new_name='Medico',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='idPaciente',
            new_name='Paciente',
        ),
    ]
