# Generated by Django 5.2.7 on 2025-10-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='atendido',
            field=models.BooleanField(default=False, help_text='Indica si el turno ya fue completado y atendido por el médico.'),
        ),
        migrations.AddField(
            model_name='turno',
            name='cancelado',
            field=models.BooleanField(default=False, help_text='Indica si el turno fue cancelado por el paciente o la clínica.'),
        ),
    ]
