# Generated by Django 5.2.7 on 2025-10-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0002_rename_idmedico_turno_medico_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['fecha_hora']},
        ),
        migrations.RemoveField(
            model_name='turno',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='hora',
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_hora',
            field=models.DateTimeField(default='2024-01-01 00:00'),
            preserve_default=False,
        ),
    ]
