# Generated by Django 5.2.7 on 2025-10-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0002_turno_atendido_turno_cancelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='id_externo',
            field=models.IntegerField(help_text='ID único del turno en la API externa (Supabase).', null=True, unique=True),
        ),
    ]
