# Generated by Django 5.2.7 on 2025-10-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0003_turno_id_externo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='id_externo',
            field=models.IntegerField(help_text='ID único del turno en la API externa (Supabase).', unique=True),
        ),
    ]
