# Generated by Django 5.2.7 on 2025-11-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0004_alter_turno_id_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='es_monitoreo',
            field=models.BooleanField(default=False, help_text='Indica si el turno corresponde a un monitoreo.'),
        ),
    ]
