# Generated by Django 5.2.7 on 2025-10-20 04:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Puncion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ovocito',
            fields=[
                ('id_ovocito', models.AutoField(primary_key=True, serialize=False)),
                ('identificador', models.CharField(help_text='Identificador único del ovocito (3-50 chars, alfanum, _ o -)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El identificador solo puede contener letras, números, guiones y guiones bajos.', regex='^[A-Za-z0-9_-]+$'), django.core.validators.MinLengthValidator(3)])),
                ('madurez', models.CharField(choices=[('muy_inmaduro', 'Muy inmaduro'), ('inmaduro', 'Inmaduro'), ('maduro', 'Maduro')], default='muy_inmaduro', max_length=20)),
                ('tipo_estado', models.CharField(choices=[('fresco', 'Fresco'), ('criopreservado', 'Criopreservado'), ('descartado', 'Descartado')], default='fresco', max_length=20)),
                ('paciente', models.ForeignKey(help_text='Paciente al que pertenece el ovocito', on_delete=django.db.models.deletion.CASCADE, related_name='ovocitos', to=settings.AUTH_USER_MODEL)),
                ('puncion', models.ForeignKey(blank=True, help_text='Punción asociada a este ovocito', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ovocitos', to='Puncion.puncion')),
            ],
            options={
                'verbose_name': 'Ovocito',
                'verbose_name_plural': 'Ovocitos',
                'ordering': ['identificador'],
            },
        ),
    ]
