# Generated by Django 5.2.7 on 2025-10-10 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ovocito',
            fields=[
                ('id_ovocito', models.AutoField(primary_key=True, serialize=False)),
                ('identificador', models.CharField(help_text='Identificador único del ovocito (3-50 chars, alfanum, _ o -)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El identificador solo puede contener letras, números, guiones y guiones bajos.', regex='^[A-Za-z0-9_-]+$'), django.core.validators.MinLengthValidator(3)])),
                ('estado', models.CharField(choices=[('muy_inmaduro', 'Muy inmaduro'), ('inmaduro', 'Inmaduro'), ('maduro', 'Maduro')], default='muy_inmaduro', max_length=20)),
                ('cripreservar', models.BooleanField(default=False)),
                ('descartado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ovocito',
                'verbose_name_plural': 'Ovocitos',
                'ordering': ['identificador'],
            },
        ),
    ]
