# Generated by Django 5.2.7 on 2025-11-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ovocito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovocito',
            name='id_rack',
            field=models.IntegerField(blank=True, help_text='Número identificador del rack de almacenamiento', null=True, verbose_name='ID del rack donde se almacena el ovocito'),
        ),
        migrations.AddField(
            model_name='ovocito',
            name='id_tanque',
            field=models.IntegerField(blank=True, help_text='Número identificador del tanque de almacenamiento', null=True, verbose_name='ID del tanque donde se almacena el ovocito'),
        ),
    ]
