# Generated by Django 5.2.7 on 2025-10-13 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ovocito', '0001_initial'),
        ('Puncion', '0002_alter_puncion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovocito',
            name='puncion',
            field=models.ForeignKey(blank=True, help_text='Punción asociada a este ovocito', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ovocitos', to='Puncion.puncion'),
        ),
    ]
