# Generated by Django 5.2.7 on 2025-10-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ovocito', '0002_ovocito_puncion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ovocito',
            old_name='estado',
            new_name='madurez',
        ),
        migrations.RemoveField(
            model_name='ovocito',
            name='cripreservar',
        ),
        migrations.RemoveField(
            model_name='ovocito',
            name='descartado',
        ),
        migrations.AddField(
            model_name='ovocito',
            name='tipo_estado',
            field=models.CharField(choices=[('fresco', 'Fresco'), ('criopreservado', 'Criopreservado'), ('descartado', 'Descartado')], default='fresco', max_length=20),
        ),
    ]
