# Generated by Django 5.2.7 on 2025-11-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ovocito', '0002_ovocito_id_rack_ovocito_id_tanque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ovocito',
            old_name='id_rack',
            new_name='rack_id',
        ),
        migrations.RenameField(
            model_name='ovocito',
            old_name='id_tanque',
            new_name='tanque_id',
        ),
    ]
