# Generated by Django 5.2.7 on 2025-11-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ovocito', '0003_rename_id_rack_ovocito_rack_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovocito',
            name='usado',
            field=models.BooleanField(default=False, help_text='Indica si el ovocito ha sido usado'),
        ),
    ]
