# Generated by Django 5.2.7 on 2025-12-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ovocito', '0004_ovocito_usado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovocito',
            name='tipo_estado',
            field=models.CharField(choices=[('fresco', 'Fresco'), ('criopreservado', 'Criopreservado'), ('descartado', 'Descartado'), ('transferido', 'Transferido')], default='fresco', max_length=20),
        ),
    ]
