# Generated by Django 5.2.7 on 2025-12-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ovocito', '0005_alter_ovocito_tipo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovocito',
            name='tipo_estado',
            field=models.CharField(choices=[('fresco', 'Fresco'), ('criopreservado', 'Criopreservado'), ('descartado', 'Descartado'), ('fertilizado', 'Fertilizado')], default='fresco', max_length=20),
        ),
    ]
