# Generated by Django 5.2.7 on 2025-10-13

from django.db import migrations, models

class Migration(migrations.Migration):

	initial = True

	dependencies = [
		('Paciente', '0001_initial'),
	]

	operations = [
		migrations.CreateModel(
			name='Puncion',
			fields=[
				('id', models.AutoField(primary_key=True, serialize=False)),
				('fecha', models.DateField()),
				('quirofano', models.CharField(max_length=50)),
				('paciente', models.ForeignKey(to='Paciente.paciente', on_delete=models.CASCADE, related_name='punciones', help_text='Paciente al que pertenece la punción')),
			],
			options={
				'verbose_name': 'Punción',
				'verbose_name_plural': 'Punciones',
				'ordering': ['-fecha'],
			},
		),
	]
