# Generated by Django 5.2.7 on 2025-10-20 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puncion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('quirofano', models.CharField(max_length=50)),
                ('paciente', models.ForeignKey(help_text='Paciente al que pertenece la punción', on_delete=django.db.models.deletion.CASCADE, related_name='punciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Punción',
                'verbose_name_plural': 'Punciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
