# Generated by Django 5.2.7 on 2025-10-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Puncion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puncion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
